name: xgboost-env

dependencies:
  - ipykernel=5.3
  - python=3.7
  - ipython=7.1
  - matplotlib=3.1
  - seaborn=0.1
  - pandas=1.0
  - numpy=1.17
  - scipy=1.4
  - pip=20.0
  - scikit-learn=0.23
  - boto3=1.9
  - statsmodels=0.11
  - py-xgboost